### ISSUE TITLE
🦠 Default color is not passed to renderer

### ISSUE THREAD

**Issue by flagadabol** [akaRicane/astar-distribution#3]
When default color is set on a color control, it is ok with the in-app renderer but the default color for the renderer is always white

Manual fix : 
- Update the color control, then the two renders resync correctly

**Comment by akaRicane** [comment]
Added a sync button to dump control state in renderers ; acts like if all controls were updated via ui. Also added the sync on renderer opening. 
Sync can be blocked with "lock feature"
